---
abstract: 'Profile object for Data::FormValidator'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-FormValidator-Profile
provides:
  Data::FormValidator::Profile:
    file: lib/Data/FormValidator/Profile.pm
    version: 0.07
requires:
  Data::FormValidator: 4.5
  List::MoreUtils: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
