---
name: Data-FormValidator-Profile
version: 0.03
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: Profile object for Data::FormValidator
license: perl
resources:
  license: ~
requires:
  Data::FormValidator: 4.5
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Data::FormValidator::Profile:
    file: lib/Data/FormValidator/Profile.pm
    version: 0.03
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
